config/routes.rb
Rails.application.routes.draw do
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos, only: [:new, :create, :destroy]
  root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    def index
        @produtos = Produto.order(nome: :desc)
        @produto_com_desconto = Produto.order(:preco).limit 1
    end
    
    def create
        produto = params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
        Produto.create produto
        redirect_to root_path
    end

    def destroy
        id = params[:id]
        Produto.destroy id
        redirect_to root_path
    end

    def busca
        @nome = params[:nome]
        @produtos = Produto.where "nome like ?", "%#{@nome}%"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Loja", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Criar novo produto", new_produto_path%>
      <% end %>
      
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :nome, @nome, class: "form-control" %>
        <%= button_to "Buscar", nil, class:"btn btn-deafult" %>
      </div>
      <% end %>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan: 1>
        </tr>
    </thead>
    <tbody>
    <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td><%= button_to "Remover", produto , method: :delete, class:"btn btn-danger",
                data: {confirm: "Tem certeza que deseja deletar o produto #{produto.nome}?"} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/produtos/index.html.erb
<html>
        <body>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <td>Nome</td>
                        <td>Descrição</td>
                        <td>Preço</td>
                        <td>Quantidade</td>
                        <td colspan: 1>
                    </tr>
                </thead>
                <tbody>
                <% @produtos.each do |produto| %>
                    <tr>
                        <td><%= produto.nome %></td>
                        <td><%= produto.descricao %></td>
                        <td><%= produto.preco %></td>
                        <td><%= produto.quantidade %></td>
                        <td><%= button_to "Remover", produto , method: :delete, class:"btn btn-danger",
                            data: {confirm: "Tem certeza que deseja deletar o produto #{produto.nome}?"} %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">Produto com desconto</h4>
            </div>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <td>Nome</td>
                        <td>Descrição</td>
                        <td>Preço</td>
                        <td>Quantidade</td>
                    </tr>
                </thead>
                <tbody>
                <% @produto_com_desconto.each do |produto| %>
                    <tr>
                        <td><%= produto.nome %></td>
                        <td><%= produto.descricao %></td>
                        <td><%= produto.preco %></td>
                        <td><%= produto.quantidade %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </body>
</html>

app/views/produtos/new.html.erb
<html>
    <body>
        <%= form_for Produto.new do |form| %>
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <%= form.label :nome %> 
                        <%= form.text_field :nome, class:"form-control" %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <%= form.label :descricao %>
                        <%= form.text_area :descricao, class:"form-control", rows:4 %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <%= form.label :preco %> 
                        <%= form.number_field :preco, step:0.01, class:"form-control" %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <%= form.label :quantidade %>
                        <%= form.number_field :quantidade, class:"form-control"  %>
                    </div>
                </div>
            </div>

            <%= form.submit "Criar", class:"btn btn-primary" %>
        <% end %>
    </body>
</html>